[target.aarch64-unknown-linux-gnu]
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "OPENSSL_STATIC",
    "OPENSSL_VENDORED"
]

[build.env]
passthrough = [
    "OPENSSL_STATIC", 
    "OPENSSL_VENDORED"
]